services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: farmos_db
      POSTGRES_USER: farmos_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-SecureF@rmPassword2024}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farmos_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  www:
    image: farmos/farmos:3.4.5
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      FARMOS_DB_HOST: db
      FARMOS_DB_NAME: farmos_db
      FARMOS_DB_USER: farmos_user
      FARMOS_DB_PASSWORD: ${DB_PASSWORD:-SecureF@rmPassword2024}
    volumes:
      - ./sites:/opt/drupal/web/sites
      - ./private:/opt/drupal/private
      - ./config:/opt/drupal/config
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/user/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  redis_data: